# server {}: a virtual host. One Nginx can serve many; this is the only one
server {
    # listen 80: the port inside the Nginx container
    listen 80;
    # server_name_;: _ is a catch-all meaning "any hostname"
    # with a real domain you'd write server_name todo.example.com; and could run several server blocks on 1 machine, each answering for a different domain
    server_name _;

    # location / {}: rules for URLs starting with / i.e everything.
    # You could add location /api/ {} later to route by path
    location / {
        # the line that does the work. Forward the request to api on port 3000
        # api is your compose service name, resolved by compose's DNS - the same mechanism that lets your app reach mongo
        proxy_pass http://api:3000;

        # enables keep-alive connections to your backend; the default 1.0 opens a new connection per request
        proxy_http_version 1.1;

        # Without the 4 proxy_set_header lines, your app sees every request as coming from Nginx, losing the real client's details
        # Host: passes the domain the client asked for
        proxy_set_header Host              $host;
        # X-Real-IP: the actual client IP. Without this, logging and rate limiting see only Nginx's address
        proxy_set_header X-Real-IP         $remote_addr;
        # X-Forwarded-For: the chain of proxies traversed
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        # X-Forwarded-Proto: whether the client used http or https, which your app can't otherwiseknow once TLS terminate at the proxy
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
